# 1. Python简介

> 基础部分是来自[菜鸟教程](http://www.runoob.com/python3)

## 1.1 Python特点

+ 解释型、脚本类、交互式、面向对象、动态数据类型的高级程序设计语言
+ Guido van Rossum，1989年底发明，1991发型1st公开版，遵循GPL协议
+ 可读性强，初学者友好
+ 重要特点
    + 易于学习、阅读、维护
    + 广泛的标准库、互动模式、可移植、可扩展
    + 数据库、GUI编程、可嵌入
        
## 1.2 重要的Python库
+ Numpy（Numerical Python），Python科学计算的基础包
+ Pandas，数据框，比R中的DataFrame更加强大
+ Mathplotlib, 绘制图表，达到出版的水平
+ Scipy，科学计算库，主要是(integrate, linalg, optimize, signal, sparse, special, stats, weave)等包

## 1.3 Ipython，交互式的Shell工具
+ Python可行计算标准工具集的组成部分，为交互式和探索式计算提供了一个强健而高效的环境
+ 类似于Mathematica的Html笔记本
+ 给予Qt框架的GUI控制台
+ 用于交互式并行和分布式计算的基础框架
+ [官网](http://ipython.org/)

## 1.4 版本选择，最新的稳定版，至少是python3
+ 库的安装
+ IDE，pycharm

## 1.5 Python基础语法

### 1.5.1 基本内容

+ 字母、数字、下划线组成，但不能以数字开头。下划线开头有特殊含义

+ 保留字

+ 其他
    + 缩进，一般是4个空格，虽然不强制，但缩进要一致
    + 多行语句，除了括号类，用‘\’进行换行
    + 注释，单行使用‘#’，多行使用3个单引号或双引号
    
+ 变量
    + 使用前进行赋值，‘=’
    
+ 数据类型
    + 基本的5种，数字、字符串、列表、元组、字典
    + 数字：不可改变，int、long、float、comples
    + 字符串：不可改变，可切片，与字符串相加、数字相乘
    + 列表：可变，有序，可切片
    + 元组：不可变，有序，可切片
    + 字典：key-value类型，key需要可hash
    
+ 类型转换
    + 转换成数字：int(x [,base]), long(x[,base]), float(x), complex(read [,[imag])
    + 转换成字符串：str(x), repr(x)
    + 转换成对象、列表、元组、集合、不可变集合、字典：eval(str),list(s),tuple(s),set(s),frozenset(s),dict(d)
    + 转换成字节码、Unicode：chr(x), unichr(x)
    + 转换成整数值、十六、八进制：ord(x), hex(x), oct(x)
    
+ 运算符
    + '+, -, *, /, //, %'
    + '==, !=, <>, <, <=, >, >='
    + '=, +=, -=, *=, /=, //=, %=, **='
    + 位运算：'&, |, ^, ~, <<, >>'
    + 逻辑运算：'and, or, not'
    + 成员运算：str比较，'in, not in'
    + 身份运算：'is, is not'
    + 优先级：指数、位(~, +(+@), -(-@))、乘除、加减、左右移、位and、位^|、比较、等于、赋值、身份、成员、逻辑， 最好使用括号

In [2]:
# 保留字
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


# 2 Python控制结构
## 2.1 条件语句
```python
if 判断条件: 
    语句1
elif
    语句2
else
    语句3
```
### 2.2 循环，for和while

+ continue，跳过当次循环
+ break，终结紧包break的循环

In [1]:
for i in range(2,100):
    for j in range(2, int(i**0.5)+1):
        if i%j==0:
            break
    else:
        print(i,end='\t')

2	3	5	7	11	13	17	19	23	29	31	37	41	43	47	53	59	61	67	71	73	79	83	89	97	

In [4]:
print([i for i in range(2,100) 
       if 0 not in (i%j for j in range(2, int(i**0.5)+1))])

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


### 2.3 数据函数

+ abs(x), fabs(x)
+ ceil(x), floor(x), 
+ log(x), log10(x), exp(x), pow(x,y), sqrt(x) 
+ max(x1, x2,...), min(x1, x2...)
+ modf(x), 
+ round(x [,n]),"4舍6入5后非零可进1,5后为0成双"
+ operator,'gt,ge,eq,le,lt'

In [13]:
import operator as op
import math
print(op.lt(-4,10), math.modf(5.4))

True (0.40000000000000036, 5.0)


In [61]:
print(round(1.4), round(1.6), round(1.152,1), 
      round(1.250,1), round(1.350,1), sep='\n')

1
2
1.2
1.2
1.4


### 2.4 随机函数
#### random
+ choice(seq)
+ randrange([start,]stop[,step])
+ random()
+ seed(x)
+ shuffle(lst)
+ uniform(x,y)
+ randint(x,y)
+ sample(seq,length)

In [22]:
import random
print(random.choice(range(10)), random.randrange(10))

8 5


In [44]:
list = [1,23,4,9] 
# shuffle的返回值是None
random.shuffle(list) 
list

[9, 1, 4, 23]

In [46]:
# 前后均闭
random.uniform(10,20)

12.22781936425191

In [35]:
print(random.random())

0.5406491546595898


In [56]:
print(random.randint(10,20))

19


In [58]:
a = 'dkelrklaerkej'
l = random.sample(a,4)
l = ''.join(l)
l

'derk'

In [59]:
a

'dkelrklaerkej'

### 2.5 其他函数

+ 三角函数，acos(x), asin(x), atan(x), atan2(y,x), cos(x), hypot(x,y),
sin(x), tan(x), degrees(x), randians(x)
+ 常量，pi,e

### 2.6 字符串 

+ 转义，'\\'
+ 运算，'+, \*, \[\], \[\:\], in, not in, r\/R, %'
+ 格式化
+ 三引号，Unicode
+ 内建函数
    + 性质
        + startswith(suffix, beg=0, end=len(string)), endswith(suffix, beg=0, end=len(string))
        + 字母、数字、数字、10进制、字母或数字、空格：isalpha(), isdigit(), isnumeric(), isdecimal(), isalnum(), isspace()
        + istitle(), isupper(), islower()
    + 解码、编码
        + bytes.decode(encoding='utf-8', erros='strict')
        + encode(encoding='utf-8', erros='strict')
    + 规整
        + 将tab替换为4空格，expandtabs(tabsize=4) 
        + strip(), lstrip(), rstrip()
        + title(), capitalize(), upper(), lower(), swapcase()
    + 对齐
        + center(width[, fillchar])
        + ljust(width[,fillchar])
        + rjust(width[,fillchar])
        + zfill(width)，返回长度为width的右对齐的原字符串，填充0
    + 查找、替换、计算
        + 查找str的开始索引位置：find找不到返回-1，index则抛出异常
            + find(str, beg=0, end=len(string))
            + rfind(str, beg=0, end=len(string))
            + index(str, beg=0, end=len(string))
            + rindex(str, beg=0, end=len(string))
        + 返回最大,小的字母，max(str), min(str)
        + 替换：replace(old, new[, max])
        + 计数：count(str, beg=0, end=len(string))
        + 切割：
            + 截取n个str分割的字符串，split(str='', num=string.count(str))
        + 创建映射：
            + 创建字符映射的转换表，对于接受两个参数的最简单的调用方式，1st参数是字符串，表示需要转换的字符，2nd参数也是字符串，表示转换的目标：maketrans()
            + 根据str给出的表（包含256个字符）转换string的字符，过滤掉的字符放到deletechar参数中：translate(table, deletechars='')


### 2.7 列表

+ 查找、切片
+ 元素赋值，=
+ 删除，del
+ 操作符，len(), max(), min(), list(seq), +, \*, in, for i in lst
+ 嵌套
+ 方法
    + append(), count(), extend(), index(), insert(index, obj), 
    pop([index=-1]), remove(obj), reverse(), sort(cmp=None, key=None, reverse=False), clear(), copy()

### 2.8 元组

+ 查找、切片
+ 无法进行元素赋值，=
+ 删除整个元组，del
+ 操作符，len(), max(), min(), tuple(seq)

### 2.9-1 集合

+ 创建，空集合set(), {}
+ 集合的'|, -, &, ^'
+ 不重复
+ 操作符，len(), str(), type()
+ 方法
    + add(), update(), copy(), 
    + clear(), remove(), discard(), pop(), difference_update(), intersection_update(), symmetric_difference_update()
    + union(), differenct(), intersection(), symmetric_difference()
    + isdisjoint(), issubset(), issupset(), in, 

### 2.9-2 字典

+ 查找，d['name'], d.get('name', default)
+ 元素赋值，d['add']='as'
+ 删除，del d['add']
+ key不能重复，不可变，不能使用列表，需要可hash
+ 操作符，len(), str(), type()
+ 方法
    + clear(), copy(), fromkeys(sep[,value]), get(key, default=None), setdefault(key, default=None), update(dict2), pop(key[,default]), popitem(), key in dict, items(), keys(), values()

In [15]:
d = {'name':'john', 'gender':'M', 'age':20}

print(d['name'], d.get('name',0))

In [17]:
d['add']='as'

d['add']

In [19]:
del d['add']

d

print(len(d), str(d), type(d))

In [23]:
seq = ('name','gender','age')
e = dict.fromkeys(seq,10)
e

{'age': 10, 'gender': 10, 'name': 10}

In [24]:
'name' in e

True

In [25]:
e.setdefault('add', 'shanghai')

e

In [27]:
e.setdefault('name',20)

10

In [28]:
e

{'add': 'shanghai', 'age': 10, 'gender': 10, 'name': 10}

In [1]:
c = range(10)

In [2]:
c=list(c)

In [3]:
c

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
c.count(1)

1

In [53]:
import math
print(math.sin(math.pi/2), math.hypot(1,2), 
      math.degrees(math.pi/2),math.radians(45), sep='\n')

1.0
2.23606797749979
90.0
0.7853981633974483


### 2.9-3 日期与时间
+ 时间元组
+ import time
+ import calendar

In [62]:
import time
time.ctime()

'Mon Sep 24 10:38:09 2018'

In [39]:
time.time()

1537753092.5256233

In [40]:
import calendar
print(calendar.month(2018,9))

   September 2018
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30



## 3 Python函数
+ def开头，后接函数标识符名称和圆括号()
+ 任何传入参数和自变量必须放在圆括号中间，圆括号之间可以用于定义参数
+ 参数传递
    + 在python中，类型属于对象，变量是没有类型的。[1,2,3,4]是list类型，‘Runoob’是String类型，变量a没有类型，她仅仅是一个对象的引用（一个指针），可以只想list对象，也可以只想string对象
    ```python
    a=[1,2,3,4]
    a='Runoob'
    ```
    + 在python中，strings, tuples, numbers是不可更改的对象，list, dict是可更改的对象。
    + 参数传递，不可变类型，值传递，不会影响对象本身；可变类型，引用传递，会对对象本身产生影响。python中一切皆对象，我们应该说**传不可变对象和传可变对象**
    
    
+ 必备参数、可选参数、关键字参数等
+ 变量的作用域：L(local), E(Enclosing), G(global), B(Built-in),由低到高依次查找

+ 匿名函数lambda
+ global、local变量
+ io
    + input, print
    + os, rename, remove
    + open之后一定要close
        + open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
        + file对象的方法
            + read(), readline(), 
            + close(), flush()刷新文件内部缓冲，直接把内部缓冲区的数据立刻写入文件。
            + next(),  seek(offset[,whence]), tell()
            + write(str), writeline(seq)
            + fileno(), isatty(),truncate([size])

+ 迭代器
    + iter(), next()
    + 使用for遍历
    + 创建一个迭代器
+ 生成器（generator）
    + 使用了yield的函数
    + 就是1个迭代器，只能用于迭代操作

In [4]:
#传不可变对象
def changeme(a):
    a = 10
    print('inner：',a)
    return

a = 5
changeme(mylist)
print('outer:',a)

inner： 10
outer: 5


In [3]:
# 传可变对象
def changeme(mylist):
    mylist.append(range(3))
    print('inner：',mylist)
    return

mylist = [10,20,30]
changeme(mylist)
print('outer:',mylist)

inner： [10, 20, 30, range(0, 3)]
outer: [10, 20, 30, range(0, 3)]


In [38]:
l = list(range(10))

it = iter(l)

print(next(it))

In [41]:
print(next(it))

for x in it:
    print(x)

In [43]:
import sys
l = list(range(11))
it = iter(l)

while True:
    try:
        print(next(it))
    except StopIteration:
        sys.exit()

0
1
2
3
4
5
6
7
8
9
10


SystemExit: 

e:\programfiles\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2918: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [1]:
class MyNumbers:
    def __iter__(self):
        self.a = 1
        return self
    
    def __next__(self):
        if self.a <=20:
            x = self.a
            self.a += 1
            return x
        else:
            raise StopIteration
    
    
myclass = MyNumbers()
myiter = iter(myclass)

for x in myiter:
    print(x, end='\t')

1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	

In [50]:
import sys

def fibonacci(n):
    a,b,counter = 0,1,0
    while True:
        if (counter>n):
            return
        yield a
        a,b=b,a+b
        counter += 1

f = fibonacci(10)

while True:
    try:
        print(next(f), end='\t')
    except StopIteration:
        sys.exit()

0	1	1	2	3	5	8	13	21	34	55	

SystemExit: 

e:\programfiles\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2918: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [29]:
list(map(lambda x: str(x), range(10)))

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [34]:
from functools import reduce
reduce(lambda x, y: x*y, range(1,10))

362880

In [32]:
?reduce

Docstring:
reduce(function, sequence[, initial]) -> value

Apply a function of two arguments cumulatively to the items of a sequence,
from left to right, so as to reduce the sequence to a single value.
For example, reduce(lambda x, y: x+y, [1, 2, 3, 4, 5]) calculates
((((1+2)+3)+4)+5).  If initial is present, it is placed before the items
of the sequence in the calculation, and serves as a default when the
sequence is empty.
Type:      builtin_function_or_method


In [1]:
try:
    fp = open('./Python数据分析_炼数/test.md','w')
    fp.write('This is test line')
except:
    print('无法写入，或找不到')

无法写入，或找不到


### 3.1 模块

> 模块是一个车包含所有你定义的函数和变量的文件，后缀名为.py, 模块可以被别的程序引入，以使用该模块中的函数等功能。

+ import语句，'import module1[, module2[, module3[,...moduleN]

In [ ]:
# !/usr/bin/python3
# Filename:support.py

def print_func(par):
    print('Hello,', par)
    return

# !/ur/bin/python3
# Filename:test.py

import support
support.print_func('Runoob')

+ 一个模块只会被导入1次，不管执行了多少次import。可以防止导入模块被一遍又一遍地执行
+ 使用from...import，不会把导入模块的名称放在当前的字符表中
+ 使用import时候的，执行查找顺序：
    + 搜索路径，由一系列目录名组成。
    + 可以通过定义环境变量来确定搜索路径
    + 搜索路径是在Python编译或安装的时候确定的，安装新的库应该也会修改。搜索路径被存储在sys模块中的path变量。
+ \_\_name\_\_属性：一个模块被另一个程序第一次引入是，起主程序将运行。
    + 在模块被引入时，可以使用\_\_name\_\_属性来使该程序块仅在该模块自身运行时执行
    + 当\_\_name\_\_的值是\_\_main\_\_时，表明模块自身在运行。

+ 内置函数dir()，可以找到模块内定义的所有名称，以1个字符串列表的形式返回
+ 如果不给定参数，dir会罗列当前定义的所有名称

In [13]:
print(dir(), sep='\t')

['In', 'Out', '_', '_10', '_12', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_dh', '_i', '_i1', '_i10', '_i11', '_i12', '_i13', '_i2', '_i3', '_i4', '_i5', '_i6', '_i7', '_i8', '_i9', '_ih', '_ii', '_iii', '_oh', 'exit', 'get_ipython', 'i', 'os', 'print_func', 'quit', 'sys']


In [14]:
a = 5

In [15]:
print(dir(), sep='\t')

['In', 'Out', '_', '_10', '_12', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_dh', '_i', '_i1', '_i10', '_i11', '_i12', '_i13', '_i14', '_i15', '_i2', '_i3', '_i4', '_i5', '_i6', '_i7', '_i8', '_i9', '_ih', '_ii', '_iii', '_oh', 'a', 'exit', 'get_ipython', 'i', 'os', 'print_func', 'quit', 'sys']


In [11]:
import os
print(dir(os), sep='\t')

['DirEntry', 'F_OK', 'MutableMapping', 'O_APPEND', 'O_BINARY', 'O_CREAT', 'O_EXCL', 'O_NOINHERIT', 'O_RANDOM', 'O_RDONLY', 'O_RDWR', 'O_SEQUENTIAL', 'O_SHORT_LIVED', 'O_TEMPORARY', 'O_TEXT', 'O_TRUNC', 'O_WRONLY', 'P_DETACH', 'P_NOWAIT', 'P_NOWAITO', 'P_OVERLAY', 'P_WAIT', 'PathLike', 'R_OK', 'SEEK_CUR', 'SEEK_END', 'SEEK_SET', 'TMP_MAX', 'W_OK', 'X_OK', '_Environ', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_execvpe', '_exists', '_exit', '_fspath', '_get_exports_list', '_putenv', '_unsetenv', '_wrap_close', 'abc', 'abort', 'access', 'altsep', 'chdir', 'chmod', 'close', 'closerange', 'cpu_count', 'curdir', 'defpath', 'device_encoding', 'devnull', 'dup', 'dup2', 'environ', 'errno', 'error', 'execl', 'execle', 'execlp', 'execlpe', 'execv', 'execve', 'execvp', 'execvpe', 'extsep', 'fdopen', 'fsdecode', 'fsencode', 'fspath', 'fstat', 'fsync', 'ftruncate', 'get_exec_path', 'get_handle_inheritable', 'get_inheritable',

In [3]:
# sys.argv包含命令行参数的列表
import sys
for i in sys.argv:
    print(i)

e:\programfiles\anaconda3\lib\site-packages\ipykernel_launcher.py
-f
C:\Users\namsu\AppData\Roaming\jupyter\runtime\kernel-0f2d46be-3cbd-4629-82c6-0ea4ab70dee5.json


In [4]:
# 包含Python解释器自动查找所需模块的路径的列表
print(sys.path)

['', 'e:\\programfiles\\anaconda3\\python36.zip', 'e:\\programfiles\\anaconda3\\DLLs', 'e:\\programfiles\\anaconda3\\lib', 'e:\\programfiles\\anaconda3', 'e:\\programfiles\\anaconda3\\lib\\site-packages', 'e:\\programfiles\\anaconda3\\lib\\site-packages\\win32', 'e:\\programfiles\\anaconda3\\lib\\site-packages\\win32\\lib', 'e:\\programfiles\\anaconda3\\lib\\site-packages\\Pythonwin', 'e:\\programfiles\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\namsu\\.ipython']


+ sys.path输出1个列表，其中第1项是空串，表示当前目录，即解释器目录
+ 可以在进本中修改sys.path来引入一些不在搜索路径中的模块

In [9]:
import os
print(os.getcwd(), os.listdir(), sep='\n')

H:\cmder\myfiles\PythonAnalysis\Jupyter_notebook\Python数据分析_炼数
['.ipynb_checkpoints', 'Python数据分析_炼数.ipynb']


+ 标准模块
    + windows下面的winreg
    + sys，内置在每一个python解析器中。sys.ps1, sys.ps2定义了主提示符和副提示符所对应的字符串

In [18]:
print(sys.ps1, sys.ps2)

In :  ...: 


In [19]:
sys.ps1='C>'

In [20]:
print('Yuck')

Yuck


In [21]:
print(sys.ps1, sys.ps2)

C> ...: 


+ 包

> 管理python模块命名空间的形式，采用‘点模块名称’，例如A.B

+ 导入1个包，python会根据sys.path中的目录来寻找这个包所包含的子目录
+ 目录只有包含1个叫做\_\_init\_\_.py的文件才会被认作是1个包，初始化文件可以包含一些初始化代码或者为\_\_all\_\_变量赋值
+ 可使用'import.., from..import..'等导入 
+ 导入语句遵循：
    + 如果报定义文件\_\_init\_\_.py存在1个叫做\_\_all\_\_的列表变量，那么在使用from package import \*的时候，把这个列表中的所有名字作为包内容导入
    + 如果没有定义，就只会把'from sound.effects import \*'中sound.effects和他定义的所有内容导入进来

In [22]:
__all__ = ['echo', 'surround', 'reverse']

In [25]:
s = 'Hello Runoob'
str(s)

'Hello Runoob'

In [27]:
# repr可以转移字符串中的特殊字符
repr(s)

"'Hello Runoob'"

In [28]:
print(repr('Hello,\nWorld'))

'Hello,\nWorld'


In [29]:
print('Hello,\nWorld')

Hello,
World


In [31]:
print('10461'.zfill(7), 'str'.rjust(5), 'str'.ljust(5), sep='\t' )

0010461	  str	str  


In [34]:
'''!a(使用ascii()),!s(使用str()),!r(使用repr())用于在格式化
某个值之前对其进行转让'''
import math
print('{!r}'.format(math.pi))

3.141592653589793


In [40]:
print('{0:.4f}'.format(math.pi))

3.1416


In [43]:
os.getcwd()

'H:\\cmder\\myfiles\\PythonAnalysis\\Jupyter_notebook\\Python数据分析_炼数'

# 4 Numpy
## 4.1 Numpy数组对象
### 4.1.1 ndarray:该对象由两部分组成
+ 实际的数据
+ 描述这些数据的元数据

## 4.2 数组的向量化


In [1]:
import numpy as np
a = np.arange(10)**2
b = np.arange(10)**3
c = a+b
c

array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810], dtype=int32)

In [2]:
import sys
from datetime import datetime

In [8]:
size = 1000
start = datetime.now()
d = sum(range(size))
delta = datetime.now()-start
print(d, delta.microseconds)

499500 0


In [9]:
size = 1000
start = datetime.now()
d = np.sum(range(size))
delta = datetime.now()-start
print(d, delta.microseconds)

499500 0


In [11]:
a = np.arange(5)
a.dtype

dtype('int32')

In [14]:
print(a, a.ndim, a.shape, a.size)

[0 1 2 3 4] 1 (5,) 5


In [24]:
np.ones_like(a)

array([1, 1, 1, 1, 1])

In [15]:
b = np.array([np.arange(2), np.arange(2)])

In [16]:
b

array([[0, 1],
       [0, 1]])

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(5,)

array([1., 1., 1., 1., 1.])

In [21]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.38332814e-321],
       [9.18824177e-312, 0.00000000e+000, 3.23815565e-319]])

In [25]:
e = np.eye(4)

In [26]:
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
e[1,1]

1.0

In [29]:
e.dtype

dtype('float64')

In [35]:
f = e.astype(np.int8)

In [36]:
f.dtype

dtype('int8')

In [37]:
g = np.array(['True','False','False','True'])

In [38]:
g.dtype

dtype('<U5')

In [39]:
g = np.array([True,False,False,True])

In [40]:
g.dtype

dtype('bool')

In [42]:
g.dtype.itemsize

1

In [44]:
f.dtype.byteorder

'|'

In [45]:
print(np.arange(7, dtype='f'))

[0. 1. 2. 3. 4. 5. 6.]


In [48]:
print(np.arange(7, dtype='D'))

[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]


In [51]:
print(np.arange(7, dtype='O'))

[0 1 2 3 4 5 6]


In [54]:
t = np.dtype('Float64')

e:\programfiles\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  """Entry point for launching an IPython kernel.


In [55]:
t.char

'd'

In [56]:
t.type

numpy.float64

In [57]:
t.str

'<f8'

In [63]:
t = np.dtype([('name', np.str_, 40), ('numitems', np.int32), 
              ('price', np.float32)])

In [59]:
print(t)

[('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')]


In [64]:
itmez = np.array([('Meaning of lice DVD', 42, 3.14), 
                  ('Butter', 13, 2.72)], dtype=t)

In [62]:
itmez

array([('Meaning of lice DVD', 42, 3.14), ('Butter', 13, 2.72)],
      dtype=[('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [65]:
s = slice(3,7,2)

In [67]:
f

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [66]:
f[s]

array([[0, 0, 0, 1]], dtype=int8)

In [68]:
f.reshape(2,8)

array([[1, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 1]], dtype=int8)

In [69]:
h = np.arange(24).reshape(2,3,4)

In [70]:
h

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [71]:
h[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
h[0,0,0]

0

In [73]:
h[:,:2,:3]

array([[[ 0,  1,  2],
        [ 4,  5,  6]],

       [[12, 13, 14],
        [16, 17, 18]]])

In [74]:
h[...,1,]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [75]:
h[::-1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [76]:
h[::-1,::-1,::-1]

array([[[23, 22, 21, 20],
        [19, 18, 17, 16],
        [15, 14, 13, 12]],

       [[11, 10,  9,  8],
        [ 7,  6,  5,  4],
        [ 3,  2,  1,  0]]])

In [79]:
s = np.array(['lily','suai','ann','lucy'])

In [80]:
s == 'lucy'

array([False, False, False,  True])

In [83]:
h = h.reshape(4,6)

In [85]:
h[s=='suai']

array([[ 6,  7,  8,  9, 10, 11]])

In [89]:
h[~(s=='ann'), 2:4]

array([[ 2,  3],
       [ 8,  9],
       [20, 21]])

In [92]:
h[(s=='lily') | (s=='suai')]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [94]:
arr = np.empty((8,4))

In [95]:
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [96]:
arr[[4,5,6,3]]

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [3., 3., 3., 3.]])

In [97]:
arr[[-4,-5,-6,-3]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [2., 2., 2., 2.],
       [5., 5., 5., 5.]])

In [100]:
arr[[2,5,6],[1,3,2]]

array([2., 5., 6.])

In [102]:
arr[[2,5,6]][:,[1,3,2]]

array([[2., 2., 2.],
       [5., 5., 5.],
       [6., 6., 6.]])

In [103]:
arr[np.ix_([2,5,6],[1,3,2])]

array([[2., 2., 2.],
       [5., 5., 5.],
       [6., 6., 6.]])

In [104]:
arr.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [105]:
arr.T.dot(arr)

array([[140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.]])

In [108]:
arr1 = arr.ravel()

In [109]:
arr1.shape

(32,)

In [107]:
arr.flatten()

array([0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4.,
       4., 4., 4., 5., 5., 5., 5., 6., 6., 6., 6., 7., 7., 7., 7.])

In [110]:
arr.transpose()

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [113]:
arr.resize((2,16))

In [114]:
arr

array([[0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.],
       [4., 4., 4., 4., 5., 5., 5., 5., 6., 6., 6., 6., 7., 7., 7., 7.]])

In [115]:
arr.T == arr.transpose()

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [117]:
b = arr * 2

In [122]:
a = arr
print(a, b, sep='\n')

[[0. 0. 0. 0. 1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]
 [4. 4. 4. 4. 5. 5. 5. 5. 6. 6. 6. 6. 7. 7. 7. 7.]]
[[ 0.  0.  0.  0.  2.  2.  2.  2.  4.  4.  4.  4.  6.  6.  6.  6.]
 [ 8.  8.  8.  8. 10. 10. 10. 10. 12. 12. 12. 12. 14. 14. 14. 14.]]


In [123]:
# hstack
print(np.hstack((a,b)))

[[ 0.  0.  0.  0.  1.  1.  1.  1.  2.  2.  2.  2.  3.  3.  3.  3.  0.  0.
   0.  0.  2.  2.  2.  2.  4.  4.  4.  4.  6.  6.  6.  6.]
 [ 4.  4.  4.  4.  5.  5.  5.  5.  6.  6.  6.  6.  7.  7.  7.  7.  8.  8.
   8.  8. 10. 10. 10. 10. 12. 12. 12. 12. 14. 14. 14. 14.]]


In [125]:
# concatenate
print(np.concatenate((a,b), axis=1))

[[ 0.  0.  0.  0.  1.  1.  1.  1.  2.  2.  2.  2.  3.  3.  3.  3.  0.  0.
   0.  0.  2.  2.  2.  2.  4.  4.  4.  4.  6.  6.  6.  6.]
 [ 4.  4.  4.  4.  5.  5.  5.  5.  6.  6.  6.  6.  7.  7.  7.  7.  8.  8.
   8.  8. 10. 10. 10. 10. 12. 12. 12. 12. 14. 14. 14. 14.]]


In [126]:
# concatenate
print(np.concatenate((a,b)))

[[ 0.  0.  0.  0.  1.  1.  1.  1.  2.  2.  2.  2.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  5.  5.  5.  5.  6.  6.  6.  6.  7.  7.  7.  7.]
 [ 0.  0.  0.  0.  2.  2.  2.  2.  4.  4.  4.  4.  6.  6.  6.  6.]
 [ 8.  8.  8.  8. 10. 10. 10. 10. 12. 12. 12. 12. 14. 14. 14. 14.]]


In [124]:
# vstack
print(np.vstack((a,b)))

[[ 0.  0.  0.  0.  1.  1.  1.  1.  2.  2.  2.  2.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  5.  5.  5.  5.  6.  6.  6.  6.  7.  7.  7.  7.]
 [ 0.  0.  0.  0.  2.  2.  2.  2.  4.  4.  4.  4.  6.  6.  6.  6.]
 [ 8.  8.  8.  8. 10. 10. 10. 10. 12. 12. 12. 12. 14. 14. 14. 14.]]


In [127]:
print(np.dstack((a,b)))

[[[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1.  2.]
  [ 1.  2.]
  [ 1.  2.]
  [ 1.  2.]
  [ 2.  4.]
  [ 2.  4.]
  [ 2.  4.]
  [ 2.  4.]
  [ 3.  6.]
  [ 3.  6.]
  [ 3.  6.]
  [ 3.  6.]]

 [[ 4.  8.]
  [ 4.  8.]
  [ 4.  8.]
  [ 4.  8.]
  [ 5. 10.]
  [ 5. 10.]
  [ 5. 10.]
  [ 5. 10.]
  [ 6. 12.]
  [ 6. 12.]
  [ 6. 12.]
  [ 6. 12.]
  [ 7. 14.]
  [ 7. 14.]
  [ 7. 14.]
  [ 7. 14.]]]


In [129]:
'np.column_stack'=='np.hstack',
'np.row_stack'=='np.vastack'

False

In [131]:
a

array([[0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.],
       [4., 4., 4., 4., 5., 5., 5., 5., 6., 6., 6., 6., 7., 7., 7., 7.]])

In [132]:
a = np.random.randn(9).reshape(3,3)

In [133]:
a

array([[ 0.72816244,  1.4814767 , -1.56732361],
       [ 1.20279917,  0.08913995,  1.51481978],
       [ 2.35100777, -0.32572369, -1.43183938]])

In [134]:
print(np.hsplit(a,3))

[array([[0.72816244],
       [1.20279917],
       [2.35100777]]), array([[ 1.4814767 ],
       [ 0.08913995],
       [-0.32572369]]), array([[-1.56732361],
       [ 1.51481978],
       [-1.43183938]])]


In [135]:
print(np.split(a, 3, axis=1))

[array([[0.72816244],
       [1.20279917],
       [2.35100777]]), array([[ 1.4814767 ],
       [ 0.08913995],
       [-0.32572369]]), array([[-1.56732361],
       [ 1.51481978],
       [-1.43183938]])]


In [137]:
print(np.vsplit(a,3))
# np.split(a,3,axis=0)

[array([[ 0.72816244,  1.4814767 , -1.56732361]]), array([[1.20279917, 0.08913995, 1.51481978]]), array([[ 2.35100777, -0.32572369, -1.43183938]])]


In [138]:
b = np.random.randn(36).reshape(3,3,4)

In [139]:
b

array([[[-0.05679176, -0.2643335 , -1.31013683,  1.94819824],
        [ 0.39964916,  1.15571622, -0.14592663,  0.66168044],
        [-1.31056608, -0.91049087, -1.04360394, -0.36298435]],

       [[-0.36639286,  0.97757816, -0.54141753, -1.10525813],
        [ 0.55336928,  0.42140586,  0.73169849,  1.25100833],
        [-1.64975271,  1.01283213,  0.65611581, -0.5481495 ]],

       [[ 0.62208675,  0.15516757, -0.8730077 ,  0.83639659],
        [ 1.98135857, -0.63980312, -0.43884765,  0.80950132],
        [ 0.61430364,  0.85875493,  0.97782188,  0.90470787]]])

In [141]:
print(np.dsplit(b,2))

[array([[[-0.05679176, -0.2643335 ],
        [ 0.39964916,  1.15571622],
        [-1.31056608, -0.91049087]],

       [[-0.36639286,  0.97757816],
        [ 0.55336928,  0.42140586],
        [-1.64975271,  1.01283213]],

       [[ 0.62208675,  0.15516757],
        [ 1.98135857, -0.63980312],
        [ 0.61430364,  0.85875493]]]), array([[[-1.31013683,  1.94819824],
        [-0.14592663,  0.66168044],
        [-1.04360394, -0.36298435]],

       [[-0.54141753, -1.10525813],
        [ 0.73169849,  1.25100833],
        [ 0.65611581, -0.5481495 ]],

       [[-0.8730077 ,  0.83639659],
        [-0.43884765,  0.80950132],
        [ 0.97782188,  0.90470787]]])]


In [142]:
print(b.ndim, b.shape, b.itemsize, b.nbytes, sep='\n')

3
(3, 3, 4)
8
288


In [143]:
c = np.array([1+2j, 3+5j])

In [144]:
c.real

array([1., 3.])

In [145]:
c.imag

array([2., 5.])

In [150]:
print(b.flat)

In [151]:
list(b.flat)

[-0.056791764128585054,
 -0.26433350485826357,
 -1.3101368268668327,
 1.9481982355125074,
 0.39964915682271485,
 1.1557162175435511,
 -0.1459266281824304,
 0.661680441163703,
 -1.3105660772780239,
 -0.9104908702940795,
 -1.0436039410715547,
 -0.3629843493391156,
 -0.36639286032079305,
 0.9775781558890008,
 -0.5414175342211609,
 -1.1052581319573302,
 0.5533692831457057,
 0.4214058622234598,
 0.7316984924541179,
 1.2510083266205652,
 -1.6497527127688398,
 1.012832131547208,
 0.6561158072875832,
 -0.5481494984355443,
 0.622086749220537,
 0.15516756662109749,
 -0.8730076979700327,
 0.8363965908039626,
 1.9813585673218048,
 -0.6398031195796792,
 -0.4388476511081683,
 0.8095013193665496,
 0.6143036412759905,
 0.858754933025587,
 0.9778218849869222,
 0.9047078684446186]

In [147]:
b.flat[2]

-1.3101368268668327

In [153]:
b.flat[[1,2]]

array([-0.2643335 , -1.31013683])

In [154]:
c

array([1.+2.j, 3.+5.j])

In [155]:
c.tolist()

[(1+2j), (3+5j)]

In [157]:
c.tostring()

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x14@'

In [159]:
np.frombuffer(c.tostring())

array([1., 2., 3., 5.])

In [163]:
np.fromstring('20:42:52', sep=':', dtype=int)

array([20, 42, 52])

In [164]:
print(c.astype(int))

[1 3]


e:\programfiles\anaconda3\lib\site-packages\ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


In [166]:
print(c.astype('complex'))

[1.+2.j 3.+5.j]
